name: Test Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - name: Check executables
        run: |
          Get-Command flashplayer

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - name: Check executables
        run: |
          which flashplayer

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - name: Check executables
        run: |
          which flashplayer
